// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com
//
// This file is included as a module by rti_temperature_subscriber_v65.rs
// It can also be run standalone to verify the generated types compile.
//
// Generated by idl-gen from tests/interop/rti/Temperature.idl
//
// IDL source: tests/interop/rti/Temperature.idl
//   module TemperatureData {
//       struct Temperature {
//           float value;
//           long timestamp;
//       };
//   };

#![allow(dead_code, clippy::all, non_snake_case)]

use hdds::core::ser::{Cdr2Decode, Cdr2Encode, CdrError};

pub mod TemperatureData {
    use super::*;

    #[derive(Debug, Clone, PartialEq)]
    pub struct Temperature {
        pub value: f32,
        pub timestamp: i32, // IDL 'long' = i32
    }

    // === CDR2 Encoding (generated by idl-gen) ===
    impl Cdr2Encode for Temperature {
        fn encode_cdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
            let mut offset: usize = 0;

            // Align to 4-byte boundary for field 'value'
            let padding = (4 - (offset % 4)) % 4;
            offset += padding;

            if dst.len() < offset + 4 {
                return Err(CdrError::BufferTooSmall);
            }
            dst[offset..offset + 4].copy_from_slice(&self.value.to_le_bytes());
            offset += 4;

            // Align to 4-byte boundary for field 'timestamp'
            let padding = (4 - (offset % 4)) % 4;
            offset += padding;

            if dst.len() < offset + 4 {
                return Err(CdrError::BufferTooSmall);
            }
            dst[offset..offset + 4].copy_from_slice(&self.timestamp.to_le_bytes());
            offset += 4;

            Ok(offset)
        }

        fn max_cdr2_size(&self) -> usize {
            8 // f32 (4) + i32 (4), no padding needed (both 4-byte aligned)
        }

        // SAFETY: type has no internal alignment requirement — both fields
        // (f32, i32) align on 4 and the local-offset path emits the same
        // bytes as a global-offset path for any 4-byte-aligned outer
        // position.
        fn encode_cdr2_le_at(
            &self,
            dst: &mut [u8],
            offset: &mut usize,
        ) -> Result<(), hdds::CdrError> {
            let len = self.encode_cdr2_le(&mut dst[*offset..])?;
            *offset += len;
            Ok(())
        }
    }

    impl Cdr2Decode for Temperature {
        fn decode_cdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
            let mut offset = 0;
            let value = Self::decode_cdr2_le_at(src, &mut offset)?;
            Ok((value, offset))
        }

        fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
            let value = f32::decode_cdr2_le_at(src, offset)?;
            let timestamp = i32::decode_cdr2_le_at(src, offset)?;
            Ok(Self { value, timestamp })
        }
    }

    // === DDS Trait Implementation (added for HDDS API compatibility) ===
    impl ::hdds::dds::DDS for Temperature {
        fn type_descriptor() -> &'static ::hdds::core::types::TypeDescriptor {
            static DESC: ::hdds::core::types::TypeDescriptor =
                ::hdds::core::types::TypeDescriptor {
                    type_id: 0x05644EB5, // FNV-1a hash of "TemperatureData::Temperature"
                    type_name: "TemperatureData::Temperature", // [OK] RTI FQN!
                    size_bytes: 8,
                    alignment: 4,
                    is_variable_size: false,
                    fields: &[
                        ::hdds::core::types::FieldLayout {
                            name: "value",
                            offset_bytes: 0,
                            field_type: ::hdds::core::types::FieldType::Primitive(
                                ::hdds::core::types::PrimitiveKind::F32,
                            ),
                            alignment: 4,
                            size_bytes: 4,
                            element_type: None,
                        },
                        ::hdds::core::types::FieldLayout {
                            name: "timestamp",
                            offset_bytes: 4,
                            field_type: ::hdds::core::types::FieldType::Primitive(
                                ::hdds::core::types::PrimitiveKind::I32, // [OK] Match RTI IDL 'long'
                            ),
                            alignment: 4,
                            size_bytes: 4,
                            element_type: None,
                        },
                    ],
                };
            &DESC
        }

        fn encode(
            &self,
            buf: &mut [u8],
            _version: ::hdds::CdrVersion,
        ) -> ::hdds::dds::Result<usize> {
            use ::hdds::core::ser::Cdr2Encode;
            self.encode_cdr2_le(buf).map_err(|e| match e {
                ::hdds::CdrError::BufferTooSmall => ::hdds::Error::BufferTooSmall,
                _ => ::hdds::Error::SerializationError,
            })
        }

        fn decode(buf: &[u8], _version: ::hdds::CdrVersion) -> ::hdds::dds::Result<Self> {
            use ::hdds::core::ser::Cdr2Decode;
            Self::decode_cdr2_le(buf)
                .map(|(val, _)| val)
                .map_err(|e| match e {
                    ::hdds::CdrError::UnexpectedEof => ::hdds::Error::SerializationError,
                    _ => ::hdds::Error::SerializationError,
                })
        }

        fn get_type_object() -> Option<::hdds::xtypes::CompleteTypeObject> {
            Some(::hdds::xtypes::CompleteTypeObject::Struct(
                ::hdds::xtypes::CompleteStructType {
                    struct_flags: ::hdds::xtypes::StructTypeFlag::IS_FINAL,
                    header: ::hdds::xtypes::CompleteStructHeader {
                        base_type: None,
                        detail: ::hdds::xtypes::CompleteTypeDetail::new(
                            "TemperatureData::Temperature",
                        ),
                    },
                    member_seq: vec![
                        ::hdds::xtypes::CompleteStructMember {
                            common: ::hdds::xtypes::CommonStructMember {
                                member_id: 0,
                                member_flags: ::hdds::xtypes::MemberFlag::empty(),
                                member_type_id: ::hdds::xtypes::TypeIdentifier::TK_FLOAT32,
                            },
                            detail: ::hdds::xtypes::CompleteMemberDetail::new("value"),
                        },
                        ::hdds::xtypes::CompleteStructMember {
                            common: ::hdds::xtypes::CommonStructMember {
                                member_id: 1,
                                member_flags: ::hdds::xtypes::MemberFlag::empty(),
                                member_type_id: ::hdds::xtypes::TypeIdentifier::TK_INT32, // [OK] RTI IDL 'long'
                            },
                            detail: ::hdds::xtypes::CompleteMemberDetail::new("timestamp"),
                        },
                    ],
                },
            ))
        }
    }
}

fn main() {
    // This file primarily provides the Temperature type for rti_temperature_subscriber_v65.rs
    // Running standalone just verifies the type definitions compile correctly.
    use TemperatureData::Temperature;
    let sample = Temperature {
        value: 23.5,
        timestamp: 1234567890,
    };
    println!("Temperature type compiled OK: {:?}", sample);
}
