// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

//! CDR2 encoding/decoding traits
//!
//! These traits define the interface for types that can be serialized/deserialized
//! using CDR2 (Common Data Representation v2) format.
//!
//! These traits are designed to match the output of hdds_gen (IDL code generator),
//! allowing seamless integration between generated types and HDDS runtime.

use std::fmt;

/// Error type for CDR2 encoding/decoding operations
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CdrError {
    /// Output buffer too small for encoded data
    BufferTooSmall,

    /// Unexpected end of input buffer during decoding
    UnexpectedEof,

    /// Invalid UTF-8 encoding in string field
    InvalidEncoding,

    /// Invalid CDR2 magic bytes in header
    InvalidMagic,

    /// Data exceeds maximum encodable size (> u32::MAX bytes)
    DataTooLarge,

    /// Other error with custom message
    Other(String),
}

impl fmt::Display for CdrError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CdrError::BufferTooSmall => write!(f, "Buffer too small for CDR2 encoding"),
            CdrError::UnexpectedEof => write!(f, "Unexpected end of buffer during CDR2 decoding"),
            CdrError::InvalidEncoding => write!(f, "Invalid UTF-8 encoding in string field"),
            CdrError::InvalidMagic => write!(f, "Invalid CDR2 magic bytes"),
            CdrError::DataTooLarge => write!(f, "Data exceeds maximum encodable size (> 4GB)"),
            CdrError::Other(msg) => write!(f, "CDR2 error: {}", msg),
        }
    }
}

impl std::error::Error for CdrError {}

/// Convert CdrError to crate::Error for API compatibility
impl From<CdrError> for crate::Error {
    fn from(e: CdrError) -> Self {
        match e {
            CdrError::BufferTooSmall => crate::Error::BufferTooSmall,
            CdrError::UnexpectedEof
            | CdrError::InvalidEncoding
            | CdrError::InvalidMagic
            | CdrError::DataTooLarge
            | CdrError::Other(_) => crate::Error::SerializationError,
        }
    }
}

/// CDR2 encoding trait (Little-Endian)
///
/// Types implementing this trait can be serialized to CDR2 wire format.
/// This trait is typically implemented by hdds_gen code generator.
///
/// # Example (generated by hdds_gen ≥ 1.1.1)
///
/// Since chantier 1.6.1, only `encode_cdr2_le_at` and `max_cdr2_size` need
/// to be provided. The legacy `encode_cdr2_le(&self, dst) -> Result<usize>`
/// has a default body that delegates here, so generated code no longer
/// emits the trivial wrapper.
///
/// ```ignore
/// impl Cdr2Encode for Point {
///     fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize)
///         -> Result<(), CdrError>
///     {
///         // Write fields, advancing *offset with each one and applying
///         // alignment relative to the global *offset (not 0).
///         Ok(())
///     }
///
///     fn max_cdr2_size(&self) -> usize {
///         24
///     }
/// }
/// ```
pub trait Cdr2Encode {
    /// Encode this value into CDR2 Little-Endian format starting at offset 0.
    ///
    /// # Arguments
    /// * `dst` - Output buffer (must be large enough, check with `max_cdr2_size()`)
    ///
    /// # Returns
    /// Number of bytes written, or `CdrError::BufferTooSmall` if buffer too small
    ///
    /// # Default impl (Chantier 1.6.1f)
    /// Promoted from REQUIRED to a default that delegates to
    /// `encode_cdr2_le_at` at offset 0. This works for any type whose
    /// `_at` body is the canonical wire path. Types that need a divergent
    /// legacy wire format (cf. `Vec<T>` / `HashMap<K,V>` / `BTreeMap<K,V>`
    /// / `Option<T>` / `[T;N]` blanket impls below — kept for symmetric
    /// roundtrip with the pre-1.6.11 unaligned `Cdr2Decode` impls)
    /// continue to override.
    fn encode_cdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        // Default body since 1.6.1f. Was REQUIRED pre-1.6.1f; now any
        // impl that mirrored this body is allowed (and encouraged) to
        // drop the override entirely.
        //
        // # Warning — do NOT delegate `_at` to this
        // The reverse direction recurses forever. If a custom
        // `encode_cdr2_le_at` impl needs the trivial wire format, write
        // it inline; do not call `self.encode_cdr2_le(...)` from inside
        // `encode_cdr2_le_at`. The same warning lives on the `_at` method
        // docstring (see below).
        let mut offset = 0;
        self.encode_cdr2_le_at(dst, &mut offset)?;
        Ok(offset)
    }

    /// Get maximum size in bytes for CDR2 encoding
    ///
    /// This is a conservative estimate (may include padding/alignment overhead).
    /// Variable-size types (strings, sequences) should use worst-case estimates.
    fn max_cdr2_size(&self) -> usize;

    /// XTypes v1.3 §7.4.3.4 — Container types (sequence, map, array)
    /// recursively serialize elements using the element type's own encoding
    /// rules. For element types without native XCDR1 encoding support
    /// (not yet implemented for standard Rust container types and primitives),
    /// fall back to the XCDR2 path. This is byte-identical to XCDR2 only
    /// when elements are ≤4-byte aligned; for 8-byte-aligned elements
    /// (double, uint64, int64) the wire format follows XCDR2 alignment
    /// rules, not strict XCDR1.
    ///
    /// Overridden by types that provide an inherent `encode_xcdr1_le`
    /// method (see hdds_gen-generated code for struct/enum/union/bitset
    /// types). Rust method resolution picks the inherent first.
    fn encode_xcdr1_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        self.encode_cdr2_le(dst)
    }

    /// Default identical to `encode_cdr2_le`. Overridden by types that
    /// provide an inherent `encode_xcdr2_le` method (hdds_gen-generated
    /// code for struct/enum/union/bitset types).
    fn encode_xcdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        self.encode_cdr2_le(dst)
    }

    /// Encode into a parent buffer at a global offset cursor.
    ///
    /// This is the spec-compliant entry point per OMG DDS-XTypes v1.3
    /// §7.4.3.4.1 Tab.15. Implementations MUST propagate `offset` to
    /// internal field encoders so alignment is computed against the
    /// real wire position rather than against `0` in a sub-buffer slice
    /// (see audit finding F01 / `cdr2_alignment` systemic for the bug
    /// that this method retires; cf. `ADR-CHANTIER-1.6-AUDIT-RESPONSE.md`
    /// §10.1 + `ADR-1.6.1-PHASE-0-CARTOGRAPHIE.md` §6.1).
    ///
    /// # Arguments
    /// * `dst` — parent buffer; the implementation writes starting at
    ///   `dst[*offset]` and advances `*offset` by the number of bytes
    ///   written (including any padding emitted for alignment).
    /// * `offset` — global cursor, mutated in-place. The caller is
    ///   responsible for any pre-call alignment; the implementation
    ///   handles its own internal alignment relative to the supplied
    ///   `*offset` value.
    ///
    /// # Returns
    /// `Ok(())` on success, `Err(CdrError::BufferTooSmall)` if `dst`
    /// is too short to hold the encoding starting at `*offset`.
    ///
    /// # Status (Chantier 1.6.1)
    /// `REQUIRED` (no default impl). The whole chantier exists to make this
    /// the canonical spec-compliant entry point and to force every
    /// `Cdr2Encode` impl to opt into the offset-propagating path. Since
    /// 1.6.1f the sibling method `encode_cdr2_le` has a default body that
    /// delegates here, so impls that want the trivial wire format do not
    /// need to write a wrapper anymore. Conversely, do NOT delegate from
    /// `_at` to `encode_cdr2_le` in a custom impl: that would call back
    /// into the default body and recurse forever.
    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError>;

    /// XTypes v1.3 §7.4.3.4 — XCDR1 offset-aware sub-encoder. Default
    /// delegates to `encode_cdr2_le_at` (XCDR2 alignment rules); generated
    /// types that implement strict XCDR1 alignment override this with an
    /// inherent method via Rust method resolution. The same byte-format
    /// caveat as `encode_xcdr1_le` applies: byte-identical to XCDR2 only
    /// when elements are ≤4-byte aligned. Codegen output (hddsgen ≥1.1.0)
    /// calls `inner.encode_xcdr1_le_at(...)` on every nested field; this
    /// default makes container/primitive blanket impls work without per-
    /// type overrides.
    fn encode_xcdr1_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        self.encode_cdr2_le_at(dst, offset)
    }

    /// XTypes v1.3 §7.4.3.4 — XCDR2 offset-aware sub-encoder. Default
    /// delegates to `encode_cdr2_le_at`; generated types override with an
    /// inherent method (hddsgen ≥1.1.0). Symmetric to `encode_xcdr2_le`.
    fn encode_xcdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        self.encode_cdr2_le_at(dst, offset)
    }
}

/// CDR2 decoding trait (Little-Endian)
///
/// Types implementing this trait can be deserialized from CDR2 wire format.
/// This trait is typically implemented by hdds_gen code generator.
///
/// # Example (generated by hdds_gen ≥ 1.2.0)
///
/// Since chantier 1.6.2f, only `decode_cdr2_le_at` (REQUIRED, spec-aligned,
/// propagates the global offset) needs to be provided. The legacy
/// `decode_cdr2_le` has a default body that delegates to `_at` at offset
/// 0 — impls that want the trivial wire format do not need to write a
/// wrapper anymore (symmetric with `Cdr2Encode::encode_cdr2_le` since
/// chantier 1.6.1f).
///
/// ```ignore
/// impl Cdr2Decode for Point {
///     fn decode_cdr2_le_at(src: &[u8], offset: &mut usize)
///         -> Result<Self, CdrError>
///     {
///         // Read fields, advancing *offset with each one and applying
///         // alignment relative to the global *offset (not 0).
///         Ok(Point { /* ... */ })
///     }
/// }
/// ```
pub trait Cdr2Decode: Sized {
    /// Decode a value from CDR2 Little-Endian format starting at offset 0.
    ///
    /// # Arguments
    /// * `src` - Input buffer containing CDR2-encoded data
    ///
    /// # Returns
    /// Tuple of (decoded value, bytes consumed), or `CdrError` on failure.
    /// Symmetric with the legacy `Cdr2Encode::encode_cdr2_le(dst) ->
    /// Result<usize, CdrError>` (encode reports bytes written, decode
    /// reports bytes consumed).
    ///
    /// # Default impl (Chantier 1.6.2f)
    /// Promoted from REQUIRED to a default that delegates to
    /// `decode_cdr2_le_at` at offset 0. This works for any type whose
    /// `_at` body is the canonical wire path. Types that need a divergent
    /// legacy wire format (cf. `Vec<T>` / `HashMap<K,V>` / `BTreeMap<K,V>`
    /// / `Option<T>` / `[T;N]` blanket impls below — kept for symmetric
    /// roundtrip with the matching legacy `encode_cdr2_le` blanket bodies
    /// that themselves diverge from the spec-correct `_at` form)
    /// continue to override.
    ///
    /// # Warning — do NOT delegate `_at` to this
    /// The reverse direction recurses forever. If a custom
    /// `decode_cdr2_le_at` impl needs the trivial wire format, write
    /// it inline; do not call `Self::decode_cdr2_le(&src[*offset..])`
    /// from inside `decode_cdr2_le_at`. The same warning lives on the
    /// `_at` method docstring (see below).
    fn decode_cdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        // Default body since 1.6.2f. Was REQUIRED pre-1.6.2f; now any
        // impl that mirrored this body is allowed (and encouraged) to
        // drop the override entirely. Symmetric with the
        // `encode_cdr2_le` default body promoted in 1.6.1f.
        let mut offset = 0;
        let value = Self::decode_cdr2_le_at(src, &mut offset)?;
        Ok((value, offset))
    }

    /// Decode a value from a parent buffer at a global offset cursor.
    ///
    /// This is the spec-compliant entry point per OMG DDS-XTypes v1.3
    /// §7.4.3.4.1 Tab.15. Implementations MUST propagate `offset` to
    /// internal field decoders so alignment is computed against the
    /// real wire position rather than against `0` in a sub-buffer slice
    /// (symmetric with `Cdr2Encode::encode_cdr2_le_at` — both methods
    /// retire the F01 / `cdr2_alignment` systemic bug on their
    /// respective paths; cf. `ADR-CHANTIER-1.6-AUDIT-RESPONSE.md`
    /// §10.15 + `ADR-1.6.2-PHASE-0-CARTOGRAPHIE.md`).
    ///
    /// # Arguments
    /// * `src` — parent buffer; the implementation reads starting at
    ///   `src[*offset]` and advances `*offset` by the number of bytes
    ///   consumed (including any alignment padding skipped).
    /// * `offset` — global cursor, mutated in-place. The caller is
    ///   responsible for any pre-call alignment; the implementation
    ///   handles its own internal alignment relative to the supplied
    ///   `*offset` value.
    ///
    /// # Returns
    /// `Ok(Self)` on success with `*offset` advanced; `Err(CdrError::
    /// UnexpectedEof)` if `src` is too short, `Err(CdrError::Invalid*)`
    /// on malformed payloads. Symmetric with `Cdr2Encode::
    /// encode_cdr2_le_at(...) -> Result<(), CdrError>` — the only
    /// asymmetry is that decode constructs `Self` while encode mutates
    /// `dst`.
    ///
    /// # Padding bytes contract
    /// The decoder SKIPS padding bytes by advancing `*offset` without
    /// validating their value (per XTypes §7.4.3.2 Table 37: "value
    /// of padded bytes left unspecified" on encode → decode must
    /// tolerate any byte pattern in the alignment gap). Validating that
    /// padding equals zero would reject conformant frames from vendors
    /// that write arbitrary bytes there.
    ///
    /// # Warning — do NOT delegate this to `decode_cdr2_le`
    /// Writing `Self::decode_cdr2_le(&src[*offset..])` inside an impl
    /// of `decode_cdr2_le_at` defeats the alignment correctness this
    /// method exists to achieve: the callee resets to offset 0 and
    /// aligns relative to the sub-buffer slice, not the global offset.
    /// Implement the decode logic natively, propagating `offset` to
    /// every inner field decoder. The same warning lives on the
    /// `Cdr2Encode::encode_cdr2_le_at` docstring.
    ///
    /// # Status (Chantier 1.6.2)
    /// `REQUIRED` (no default impl on purpose, mirroring
    /// `encode_cdr2_le_at`). The migration explicitly opts out of
    /// opt-in correctness so the compiler enforces exhaustive coverage
    /// of all `Cdr2Decode` impls — each unmigrated impl surfaces as an
    /// E0046 build error rather than silently falling back to a
    /// (broken) default body. Since 1.6.2f the sibling method
    /// `decode_cdr2_le` has a default body that delegates here, so
    /// impls that want the trivial wire format do not need to write a
    /// wrapper anymore. Conversely, do NOT delegate from `_at` to
    /// `decode_cdr2_le` in a custom impl: that would call back into the
    /// default body and recurse forever.
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError>;

    /// XTypes v1.3 §7.4.3.4 — Symmetric fallback for XCDR1 decoding.
    /// See `Cdr2Encode::encode_xcdr1_le` for rationale. Overridden by
    /// types that provide an inherent `decode_xcdr1_le` method
    /// (hdds_gen-generated code for struct/enum/union/bitset types).
    fn decode_xcdr1_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        Self::decode_cdr2_le(src)
    }

    /// Default identical to `decode_cdr2_le`. Overridden by types that
    /// provide an inherent `decode_xcdr2_le` method (hdds_gen-generated
    /// code for struct/enum/union/bitset types).
    fn decode_xcdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        Self::decode_cdr2_le(src)
    }

    /// XTypes v1.3 §7.4.3.4 — XCDR1 offset-aware sub-decoder. Default
    /// delegates to `decode_cdr2_le_at` (XCDR2 alignment rules, cap-4);
    /// generated types that implement strict XCDR1 alignment (natural
    /// align without cap) override this with an inherent method via
    /// Rust method resolution. The same byte-format caveat as
    /// `decode_xcdr1_le` applies: byte-identical to XCDR2 only when
    /// elements are ≤4-byte aligned. Codegen output (hddsgen ≥1.2.0)
    /// calls `inner.decode_xcdr1_le_at(...)` on every nested field;
    /// this default makes container/primitive blanket impls work
    /// without per-type overrides. Symmetric with
    /// `Cdr2Encode::encode_xcdr1_le_at`.
    fn decode_xcdr1_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        Self::decode_cdr2_le_at(src, offset)
    }

    /// XTypes v1.3 §7.4.3.4 — XCDR2 offset-aware sub-decoder. Default
    /// delegates to `decode_cdr2_le_at`; generated types override with
    /// an inherent method (hddsgen ≥1.2.0). Symmetric with
    /// `Cdr2Encode::encode_xcdr2_le_at`.
    fn decode_xcdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        Self::decode_cdr2_le_at(src, offset)
    }
}

// DDS trait is defined in crate::dds::DDS (with type_descriptor, encode_cdr2, decode_cdr2)
// We provide Cdr2Encode/Cdr2Decode as lower-level traits that hdds_gen generates.
// A blanket impl in api/mod.rs bridges Cdr2Encode/Cdr2Decode -> api::DDS.

// ============================================================================
// Standard Type Implementations
// ============================================================================

/// CDR2 encoding for String
///
/// CDR2 string format:
/// - u32 length (number of characters, NOT including null terminator)
/// - UTF-8 bytes
/// - null terminator (0x00)
impl Cdr2Encode for String {
    fn max_cdr2_size(&self) -> usize {
        4 + self.len() + 1
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        let bytes = self.as_bytes();
        let str_len = bytes.len();
        let cdr_len: u32 = (str_len + 1)
            .try_into()
            .map_err(|_| CdrError::DataTooLarge)?;

        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 + str_len + 1 > dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        dst[*offset..*offset + pad].fill(0);
        *offset += pad;
        dst[*offset..*offset + 4].copy_from_slice(&cdr_len.to_le_bytes());
        *offset += 4;
        dst[*offset..*offset + str_len].copy_from_slice(bytes);
        *offset += str_len;
        dst[*offset] = 0;
        *offset += 1;
        Ok(())
    }
}

/// CDR2 decoding for String
impl Cdr2Decode for String {
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        // Pad to align 4 (u32 length prefix).
        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 > src.len() {
            return Err(CdrError::UnexpectedEof);
        }
        *offset += pad;
        let mut len_bytes = [0u8; 4];
        len_bytes.copy_from_slice(&src[*offset..*offset + 4]);
        let cdr_len = u32::from_le_bytes(len_bytes) as usize;
        *offset += 4;

        if *offset + cdr_len > src.len() {
            return Err(CdrError::UnexpectedEof);
        }

        // Read string bytes (strip null terminator)
        let str_len = cdr_len.saturating_sub(1);
        let s = std::str::from_utf8(&src[*offset..*offset + str_len])
            .map_err(|_| CdrError::InvalidEncoding)?
            .to_string();
        *offset += cdr_len;

        Ok(s)
    }
}

// ============================================================================
// Primitive Type Implementations
// ============================================================================

macro_rules! impl_cdr2_primitive {
    ($ty:ty, $size:expr) => {
        impl Cdr2Encode for $ty {
            fn max_cdr2_size(&self) -> usize {
                $size
            }

            /// Spec-compliant XCDR2 primitive encoding per
            /// DDS-XTypes v1.3 §7.4.3.4.1 Tab.15. Alignment caps at 4 for
            /// 8-byte primitives (i64/u64/f64); smaller types align on
            /// their own size. Padding bytes are written as zeros to
            /// match Fast DDS / Connext / OpenDDS / Cyclone DDS wire
            /// output (XCDR2 §7.4.3.4.2 mandates zero padding for
            /// reproducible hashing of TypeObject byte sequences).
            fn encode_cdr2_le_at(
                &self,
                dst: &mut [u8],
                offset: &mut usize,
            ) -> Result<(), CdrError> {
                let align: usize = if $size > 4 { 4 } else { $size };
                let pad = (align - (*offset % align)) % align;
                if *offset + pad + $size > dst.len() {
                    return Err(CdrError::BufferTooSmall);
                }
                dst[*offset..*offset + pad].fill(0);
                *offset += pad;
                dst[*offset..*offset + $size].copy_from_slice(&self.to_le_bytes());
                *offset += $size;
                Ok(())
            }
        }

        impl Cdr2Decode for $ty {
            /// Spec-compliant XCDR2 primitive decoding per
            /// DDS-XTypes v1.3 §7.4.3.4.1 Tab.15. Alignment caps at 4
            /// for 8-byte primitives (i64/u64/f64); smaller types
            /// align on their own size. Padding bytes are SKIPPED
            /// without validating their value per §7.4.3.2 Table 37
            /// ("value of padded bytes left unspecified" on encode →
            /// decoder must tolerate any byte pattern in the alignment
            /// gap rather than reject conformant frames from vendors
            /// that write arbitrary bytes there).
            fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
                let align: usize = if $size > 4 { 4 } else { $size };
                let pad = (align - (*offset % align)) % align;
                if *offset + pad + $size > src.len() {
                    return Err(CdrError::UnexpectedEof);
                }
                // Skip pad bytes WITHOUT validation per XCDR2 §7.4.3.2 Table 37.
                *offset += pad;
                let mut buf = [0u8; $size];
                buf.copy_from_slice(&src[*offset..*offset + $size]);
                *offset += $size;
                Ok(<$ty>::from_le_bytes(buf))
            }
        }
    };
}

impl_cdr2_primitive!(i8, 1);
impl_cdr2_primitive!(u8, 1);
impl_cdr2_primitive!(i16, 2);
impl_cdr2_primitive!(u16, 2);
impl_cdr2_primitive!(i32, 4);
impl_cdr2_primitive!(u32, 4);
impl_cdr2_primitive!(i64, 8);
impl_cdr2_primitive!(u64, 8);
impl_cdr2_primitive!(f32, 4);
impl_cdr2_primitive!(f64, 8);

// ============================================================================
// Vec<T> Implementation
// ============================================================================

// NOTE: encode_cdr2_le keeps the legacy sub-buffer body — it does NOT
// fall back to the new (1.6.1f) default impl that delegates to
// encode_cdr2_le_at. Reason: encode_cdr2_le_at aligns inner elements
// per the XCDR2 spec, while the symmetric Cdr2Decode for Vec<T> reads
// elements without alignment via sub-buffer slicing (no decode_cdr2_le_at
// exists yet on the trait). Switching the encoder to delegate would emit
// aligned bytes that the legacy decoder cannot read back symmetrically.
// The two paths are intentionally separate wire formats: _le for legacy
// roundtrip contracts, _at for spec-aligned offset propagation in composite
// outer encoders. Migration of the decoder to a symmetric aligned path
// (decode_cdr2_le_at) is tracked as sous-chantier 1.6.11 in
// ADR-CHANTIER-1.6 §10.15.
impl<T: Cdr2Encode> Cdr2Encode for Vec<T> {
    fn encode_cdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        let mut offset = 0;

        // Write sequence length (u32)
        let len = self.len() as u32;
        if dst.len() < 4 {
            return Err(CdrError::BufferTooSmall);
        }
        dst[offset..offset + 4].copy_from_slice(&len.to_le_bytes());
        offset += 4;

        // Write each element
        for elem in self {
            let used = elem.encode_cdr2_le(&mut dst[offset..])?;
            offset += used;
        }

        Ok(offset)
    }

    fn max_cdr2_size(&self) -> usize {
        // Conservative estimate: 4 bytes for length + sum of element sizes
        4 + self.iter().map(|e| e.max_cdr2_size()).sum::<usize>()
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        let len = u32::try_from(self.len()).map_err(|_| CdrError::DataTooLarge)?;
        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 > dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        dst[*offset..*offset + pad].fill(0);
        *offset += pad;
        dst[*offset..*offset + 4].copy_from_slice(&len.to_le_bytes());
        *offset += 4;
        for elem in self {
            elem.encode_cdr2_le_at(dst, offset)?;
        }
        Ok(())
    }
}

impl<T: Cdr2Decode> Cdr2Decode for Vec<T> {
    fn decode_cdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        let mut offset = 0;

        // Read sequence length
        if src.len() < 4 {
            return Err(CdrError::UnexpectedEof);
        }
        let len = u32::from_le_bytes([src[0], src[1], src[2], src[3]]) as usize;
        offset += 4;

        // Guard against bogus lengths: each element is at least 1 byte
        if len > src.len().saturating_sub(offset) {
            return Err(CdrError::UnexpectedEof);
        }

        // Read elements
        let mut vec = Vec::with_capacity(len);
        for _ in 0..len {
            let (elem, used) = T::decode_cdr2_le(&src[offset..])?;
            vec.push(elem);
            offset += used;
        }

        Ok((vec, offset))
    }

    /// Spec-aligned decoder symmetric with `encode_cdr2_le_at`:
    /// - Pads to 4 before the u32 length prefix (XCDR2 §7.4.3.4.1 Tab.15).
    /// - Pad bytes are SKIPPED without validating their value
    ///   (§7.4.3.2 Table 37: "value of padded bytes left unspecified").
    /// - Delegates each element to `T::decode_cdr2_le_at` so the global
    ///   cursor propagates through nested types.
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 > src.len() {
            return Err(CdrError::UnexpectedEof);
        }
        *offset += pad;
        let mut len_bytes = [0u8; 4];
        len_bytes.copy_from_slice(&src[*offset..*offset + 4]);
        let len = u32::from_le_bytes(len_bytes) as usize;
        *offset += 4;

        // Guard against bogus lengths: each element is at least 1 byte.
        if len > src.len().saturating_sub(*offset) {
            return Err(CdrError::UnexpectedEof);
        }

        let mut vec = Vec::with_capacity(len);
        for _ in 0..len {
            vec.push(T::decode_cdr2_le_at(src, offset)?);
        }
        Ok(vec)
    }
}

// ============================================================================
// HashMap<K, V> Implementation
// ============================================================================

// NOTE: encode_cdr2_le keeps the legacy sub-buffer body. See the same
// note on `impl Cdr2Encode for Vec<T>` for the rationale (legacy decoder
// does not align; encoder must stay symmetric).
impl<K: Cdr2Encode, V: Cdr2Encode> Cdr2Encode for std::collections::HashMap<K, V> {
    fn encode_cdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        let mut offset = 0;

        // Write map length (u32)
        let len = self.len() as u32;
        if dst.len() < 4 {
            return Err(CdrError::BufferTooSmall);
        }
        dst[offset..offset + 4].copy_from_slice(&len.to_le_bytes());
        offset += 4;

        // Write each key-value pair
        for (key, value) in self {
            let used = key.encode_cdr2_le(&mut dst[offset..])?;
            offset += used;
            let used = value.encode_cdr2_le(&mut dst[offset..])?;
            offset += used;
        }

        Ok(offset)
    }

    fn max_cdr2_size(&self) -> usize {
        // Conservative estimate
        4 + self.len() * 64 // rough estimate per entry
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        let len = u32::try_from(self.len()).map_err(|_| CdrError::DataTooLarge)?;
        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 > dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        dst[*offset..*offset + pad].fill(0);
        *offset += pad;
        dst[*offset..*offset + 4].copy_from_slice(&len.to_le_bytes());
        *offset += 4;
        for (key, value) in self {
            key.encode_cdr2_le_at(dst, offset)?;
            value.encode_cdr2_le_at(dst, offset)?;
        }
        Ok(())
    }
}

impl<K, V> Cdr2Decode for std::collections::HashMap<K, V>
where
    K: Cdr2Decode + std::cmp::Eq + std::hash::Hash,
    V: Cdr2Decode,
{
    fn decode_cdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        let mut offset = 0;

        // Read map length
        if src.len() < 4 {
            return Err(CdrError::UnexpectedEof);
        }
        let len = u32::from_le_bytes([src[0], src[1], src[2], src[3]]) as usize;
        offset += 4;

        // Guard against bogus lengths: each KV pair is at least 2 bytes
        if len > src.len().saturating_sub(offset) / 2 {
            return Err(CdrError::UnexpectedEof);
        }

        // Read key-value pairs
        let mut map = std::collections::HashMap::with_capacity(len);
        for _ in 0..len {
            let (key, used) = K::decode_cdr2_le(&src[offset..])?;
            offset += used;
            let (value, used) = V::decode_cdr2_le(&src[offset..])?;
            offset += used;
            map.insert(key, value);
        }

        Ok((map, offset))
    }

    /// Spec-aligned decoder symmetric with `encode_cdr2_le_at`. See the
    /// `Vec<T>::decode_cdr2_le_at` docstring for the alignment + pad-skip
    /// contract.
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 > src.len() {
            return Err(CdrError::UnexpectedEof);
        }
        *offset += pad;
        let mut len_bytes = [0u8; 4];
        len_bytes.copy_from_slice(&src[*offset..*offset + 4]);
        let len = u32::from_le_bytes(len_bytes) as usize;
        *offset += 4;

        // Guard against bogus lengths: each KV pair is at least 2 bytes.
        if len > src.len().saturating_sub(*offset) / 2 {
            return Err(CdrError::UnexpectedEof);
        }

        let mut map = std::collections::HashMap::with_capacity(len);
        for _ in 0..len {
            let key = K::decode_cdr2_le_at(src, offset)?;
            let value = V::decode_cdr2_le_at(src, offset)?;
            map.insert(key, value);
        }
        Ok(map)
    }
}

/// CDR2 encoding for &str (borrows to String encoding)
impl Cdr2Encode for &str {
    fn max_cdr2_size(&self) -> usize {
        4 + self.len() + 1
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        let bytes = self.as_bytes();
        let str_len = bytes.len();
        let cdr_len: u32 = (str_len + 1)
            .try_into()
            .map_err(|_| CdrError::DataTooLarge)?;

        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 + str_len + 1 > dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        dst[*offset..*offset + pad].fill(0);
        *offset += pad;
        dst[*offset..*offset + 4].copy_from_slice(&cdr_len.to_le_bytes());
        *offset += 4;
        dst[*offset..*offset + str_len].copy_from_slice(bytes);
        *offset += str_len;
        dst[*offset] = 0;
        *offset += 1;
        Ok(())
    }
}

// ============================================================================
// bool Implementation (XTypes 1.3 Section 7.4.1.3)
// CDR2 boolean: 1 byte, 0x00 = false, 0x01 = true
// ============================================================================

impl Cdr2Encode for bool {
    fn max_cdr2_size(&self) -> usize {
        1
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        if *offset >= dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        dst[*offset] = u8::from(*self);
        *offset += 1;
        Ok(())
    }
}

impl Cdr2Decode for bool {
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        if *offset >= src.len() {
            return Err(CdrError::UnexpectedEof);
        }
        let byte = src[*offset];
        *offset += 1;
        match byte {
            0 => Ok(false),
            1 => Ok(true),
            v => Err(CdrError::Other(format!("invalid boolean value: {v}"))),
        }
    }
}

// ============================================================================
// char Implementation (XTypes 1.3 Section 7.4.1.4 -- char8 only)
// CDR2 char8: 1 byte, ASCII range
// ============================================================================

impl Cdr2Encode for char {
    fn max_cdr2_size(&self) -> usize {
        1
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        if *offset >= dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        if !self.is_ascii() {
            return Err(CdrError::InvalidEncoding);
        }
        dst[*offset] = *self as u8;
        *offset += 1;
        Ok(())
    }
}

impl Cdr2Decode for char {
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        if *offset >= src.len() {
            return Err(CdrError::UnexpectedEof);
        }
        // char8: any byte value maps to a char (ASCII subset per spec,
        // but we accept the full u8 range for interop tolerance)
        let value = src[*offset] as char;
        *offset += 1;
        Ok(value)
    }
}

// ============================================================================
// [T; N] Implementation (XTypes 1.3 Section 7.4.4.2 -- fixed-size array)
// CDR2 array: N elements encoded sequentially, NO length prefix
// ============================================================================

// NOTE: encode_cdr2_le keeps the legacy sub-buffer body. See the same
// note on `impl Cdr2Encode for Vec<T>` for the rationale.
impl<T: Cdr2Encode, const N: usize> Cdr2Encode for [T; N] {
    fn encode_cdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        let mut offset = 0;
        for elem in self {
            let n = elem.encode_cdr2_le(&mut dst[offset..])?;
            offset += n;
        }
        Ok(offset)
    }
    fn max_cdr2_size(&self) -> usize {
        self.iter().map(|e| e.max_cdr2_size()).sum()
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        for elem in self {
            elem.encode_cdr2_le_at(dst, offset)?;
        }
        Ok(())
    }
}

impl<T: Cdr2Decode + Default + Copy, const N: usize> Cdr2Decode for [T; N] {
    fn decode_cdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        let mut arr = [T::default(); N];
        let mut offset = 0;
        for slot in &mut arr {
            let (val, n) = T::decode_cdr2_le(&src[offset..])?;
            *slot = val;
            offset += n;
        }
        Ok((arr, offset))
    }

    /// Spec-aligned decoder symmetric with `encode_cdr2_le_at`: no length
    /// prefix (fixed-size array), each element via `T::decode_cdr2_le_at`
    /// so the global cursor propagates uniformly.
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        let mut arr = [T::default(); N];
        for slot in &mut arr {
            *slot = T::decode_cdr2_le_at(src, offset)?;
        }
        Ok(arr)
    }
}

// ============================================================================
// Option<T> Implementation (XTypes 1.3 Section 7.4.3.5 -- optional member)
// CDR2 optional: 1-byte presence flag (0x00 absent, 0x01 present) + value
// ============================================================================

// NOTE: encode_cdr2_le keeps the legacy unaligned body — Option<u32>
// produces 5 bytes (1 flag + 4 unaligned u32) here, while
// encode_cdr2_le_at aligns to 4 after the flag (8 bytes total).
// The legacy decoder Cdr2Decode for Option<T> reads without alignment;
// changing the encoder would break roundtrip symmetry. Spec-aligned
// optional encoding for composite outer types goes through the
// _at path, not this method. Symmetric `decode_cdr2_le_at` migration is
// tracked as sous-chantier 1.6.11 in ADR-CHANTIER-1.6 §10.15.
impl<T: Cdr2Encode> Cdr2Encode for Option<T> {
    fn encode_cdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        if dst.is_empty() {
            return Err(CdrError::BufferTooSmall);
        }
        match self {
            None => {
                dst[0] = 0;
                Ok(1)
            }
            Some(val) => {
                dst[0] = 1;
                let n = val.encode_cdr2_le(&mut dst[1..])?;
                Ok(1 + n)
            }
        }
    }
    fn max_cdr2_size(&self) -> usize {
        match self {
            None => 1,
            Some(val) => 1 + val.max_cdr2_size(),
        }
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        if *offset >= dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        match self {
            None => {
                dst[*offset] = 0;
                *offset += 1;
                Ok(())
            }
            Some(val) => {
                dst[*offset] = 1;
                *offset += 1;
                val.encode_cdr2_le_at(dst, offset)
            }
        }
    }
}

impl<T: Cdr2Decode> Cdr2Decode for Option<T> {
    fn decode_cdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        if src.is_empty() {
            return Err(CdrError::UnexpectedEof);
        }
        match src[0] {
            0 => Ok((None, 1)),
            1 => {
                let (val, n) = T::decode_cdr2_le(&src[1..])?;
                Ok((Some(val), 1 + n))
            }
            v => Err(CdrError::Other(format!("invalid optional flag: {v}"))),
        }
    }

    /// Spec-aligned decoder symmetric with `encode_cdr2_le_at`: 1-byte
    /// presence flag (no alignment requirement), then the value via
    /// `T::decode_cdr2_le_at` which applies its own alignment relative
    /// to the post-flag offset.
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        if *offset >= src.len() {
            return Err(CdrError::UnexpectedEof);
        }
        let flag = src[*offset];
        *offset += 1;
        match flag {
            0 => Ok(None),
            1 => Ok(Some(T::decode_cdr2_le_at(src, offset)?)),
            v => Err(CdrError::Other(format!("invalid optional flag: {v}"))),
        }
    }
}

// ============================================================================
// BTreeMap<K, V> Implementation
// Same wire format as HashMap: u32 length + sequence of (K, V) pairs.
// Deterministic iteration order (sorted by key).
// ============================================================================

// NOTE: encode_cdr2_le keeps the legacy sub-buffer body. See the same
// note on `impl Cdr2Encode for Vec<T>` for the rationale.
impl<K: Cdr2Encode + Ord, V: Cdr2Encode> Cdr2Encode for std::collections::BTreeMap<K, V> {
    fn encode_cdr2_le(&self, dst: &mut [u8]) -> Result<usize, CdrError> {
        if dst.len() < 4 {
            return Err(CdrError::BufferTooSmall);
        }
        let len = self.len() as u32;
        dst[0..4].copy_from_slice(&len.to_le_bytes());
        let mut offset = 4;
        for (key, value) in self {
            let n = key.encode_cdr2_le(&mut dst[offset..])?;
            offset += n;
            let n = value.encode_cdr2_le(&mut dst[offset..])?;
            offset += n;
        }
        Ok(offset)
    }
    fn max_cdr2_size(&self) -> usize {
        4 + self.len() * 64
    }

    fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
        let len = u32::try_from(self.len()).map_err(|_| CdrError::DataTooLarge)?;
        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 > dst.len() {
            return Err(CdrError::BufferTooSmall);
        }
        dst[*offset..*offset + pad].fill(0);
        *offset += pad;
        dst[*offset..*offset + 4].copy_from_slice(&len.to_le_bytes());
        *offset += 4;
        for (key, value) in self {
            key.encode_cdr2_le_at(dst, offset)?;
            value.encode_cdr2_le_at(dst, offset)?;
        }
        Ok(())
    }
}

impl<K, V> Cdr2Decode for std::collections::BTreeMap<K, V>
where
    K: Cdr2Decode + Ord,
    V: Cdr2Decode,
{
    fn decode_cdr2_le(src: &[u8]) -> Result<(Self, usize), CdrError> {
        if src.len() < 4 {
            return Err(CdrError::UnexpectedEof);
        }
        let len = u32::from_le_bytes([src[0], src[1], src[2], src[3]]) as usize;
        let mut offset = 4;
        if len > src.len().saturating_sub(offset) / 2 {
            return Err(CdrError::UnexpectedEof);
        }
        let mut map = std::collections::BTreeMap::new();
        for _ in 0..len {
            let (key, n) = K::decode_cdr2_le(&src[offset..])?;
            offset += n;
            let (value, n) = V::decode_cdr2_le(&src[offset..])?;
            offset += n;
            map.insert(key, value);
        }
        Ok((map, offset))
    }

    /// Spec-aligned decoder symmetric with `encode_cdr2_le_at`. See the
    /// `Vec<T>::decode_cdr2_le_at` docstring for the alignment + pad-skip
    /// contract.
    fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
        let pad = (4 - (*offset % 4)) % 4;
        if *offset + pad + 4 > src.len() {
            return Err(CdrError::UnexpectedEof);
        }
        *offset += pad;
        let mut len_bytes = [0u8; 4];
        len_bytes.copy_from_slice(&src[*offset..*offset + 4]);
        let len = u32::from_le_bytes(len_bytes) as usize;
        *offset += 4;

        if len > src.len().saturating_sub(*offset) / 2 {
            return Err(CdrError::UnexpectedEof);
        }

        let mut map = std::collections::BTreeMap::new();
        for _ in 0..len {
            let key = K::decode_cdr2_le_at(src, offset)?;
            let value = V::decode_cdr2_le_at(src, offset)?;
            map.insert(key, value);
        }
        Ok(map)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Test struct implementing CDR2 traits manually
    #[derive(Debug, Clone, PartialEq)]
    struct TestPoint {
        x: i32,
        y: i32,
    }

    impl Cdr2Encode for TestPoint {
        fn max_cdr2_size(&self) -> usize {
            8
        }

        fn encode_cdr2_le_at(&self, dst: &mut [u8], offset: &mut usize) -> Result<(), CdrError> {
            self.x.encode_cdr2_le_at(dst, offset)?;
            self.y.encode_cdr2_le_at(dst, offset)?;
            Ok(())
        }
    }

    impl Cdr2Decode for TestPoint {
        fn decode_cdr2_le_at(src: &[u8], offset: &mut usize) -> Result<Self, CdrError> {
            let x = i32::decode_cdr2_le_at(src, offset)?;
            let y = i32::decode_cdr2_le_at(src, offset)?;
            Ok(TestPoint { x, y })
        }
    }

    #[test]
    fn test_cdr2_encode_decode_roundtrip() {
        let point = TestPoint { x: 42, y: 123 };
        let mut buf = vec![0u8; 256];

        // Encode
        let encoded_len = point
            .encode_cdr2_le(&mut buf)
            .expect("Encode should succeed");
        assert_eq!(encoded_len, 8);

        // Decode
        let (decoded, used) =
            TestPoint::decode_cdr2_le(&buf[..encoded_len]).expect("Decode should succeed");
        assert_eq!(decoded, point);
        assert_eq!(used, 8);
    }

    #[test]
    fn test_buffer_too_small() {
        let point = TestPoint { x: 42, y: 123 };
        let mut buf = vec![0u8; 4]; // Too small

        let result = point.encode_cdr2_le(&mut buf);
        assert_eq!(result, Err(CdrError::BufferTooSmall));
    }

    #[test]
    fn test_unexpected_eof() {
        let buf = vec![0u8; 4]; // Too small for decode

        let result = TestPoint::decode_cdr2_le(&buf);
        assert_eq!(result, Err(CdrError::UnexpectedEof));
    }

    // DDS trait test removed - DDS is defined in api::DDS, not here

    #[test]
    fn test_cdr_error_display() {
        assert_eq!(
            CdrError::BufferTooSmall.to_string(),
            "Buffer too small for CDR2 encoding"
        );
        assert_eq!(
            CdrError::UnexpectedEof.to_string(),
            "Unexpected end of buffer during CDR2 decoding"
        );
        assert_eq!(
            CdrError::InvalidEncoding.to_string(),
            "Invalid UTF-8 encoding in string field"
        );
    }

    #[test]
    fn test_cdr_error_to_crate_error() {
        let cdr_err = CdrError::BufferTooSmall;
        let _crate_err: crate::Error = cdr_err.into();
        // Should compile and convert successfully
    }

    #[test]
    fn test_string_encode_decode_roundtrip() {
        let original = "Hello, CDR2!".to_string();
        let mut buf = vec![0u8; 256];

        // Encode
        let encoded_len = original
            .encode_cdr2_le(&mut buf)
            .expect("Encode should succeed");
        // 4 (length) + 12 (chars) + 1 (null) = 17
        assert_eq!(encoded_len, 17);

        // Verify wire format: CDR length includes null terminator
        assert_eq!(&buf[0..4], &13u32.to_le_bytes()); // length = 13 (12 chars + null)
        assert_eq!(&buf[4..16], b"Hello, CDR2!");
        assert_eq!(buf[16], 0); // null terminator

        // Decode
        let (decoded, used) =
            String::decode_cdr2_le(&buf[..encoded_len]).expect("Decode should succeed");
        assert_eq!(decoded, original);
        assert_eq!(used, 17);
    }

    #[test]
    fn test_string_empty() {
        let original = String::new();
        let mut buf = vec![0u8; 256];

        let encoded_len = original
            .encode_cdr2_le(&mut buf)
            .expect("Encode should succeed");
        assert_eq!(encoded_len, 5); // 4 (length=1, includes null) + 1 (null)

        let (decoded, used) =
            String::decode_cdr2_le(&buf[..encoded_len]).expect("Decode should succeed");
        assert_eq!(decoded, original);
        assert_eq!(used, 5);
    }

    // ================================================================
    // bool tests (GAP-001)
    // ================================================================

    #[test]
    fn test_bool_true_roundtrip() {
        let mut buf = [0u8; 1];
        let n = true.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 1);
        assert_eq!(buf[0], 1);
        let (val, n) = bool::decode_cdr2_le(&buf).unwrap();
        assert!(val);
        assert_eq!(n, 1);
    }

    #[test]
    fn test_bool_false_roundtrip() {
        let mut buf = [0u8; 1];
        let n = false.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 1);
        assert_eq!(buf[0], 0);
        let (val, n) = bool::decode_cdr2_le(&buf).unwrap();
        assert!(!val);
        assert_eq!(n, 1);
    }

    #[test]
    fn test_bool_invalid_value() {
        let buf = [2u8];
        let result = bool::decode_cdr2_le(&buf);
        assert!(result.is_err());
    }

    // ================================================================
    // char tests (GAP-005)
    // ================================================================

    #[test]
    fn test_char_roundtrip() {
        let mut buf = [0u8; 1];
        let n = 'A'.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 1);
        assert_eq!(buf[0], b'A');
        let (val, n) = char::decode_cdr2_le(&buf).unwrap();
        assert_eq!(val, 'A');
        assert_eq!(n, 1);
    }

    #[test]
    fn test_char_non_ascii_rejected() {
        let mut buf = [0u8; 4];
        let result = '\u{00E9}'.encode_cdr2_le(&mut buf); // e-acute
        assert!(result.is_err());
    }

    // ================================================================
    // [T; N] tests (GAP-002)
    // ================================================================

    #[test]
    fn test_array_u32_roundtrip() {
        let arr: [u32; 3] = [10, 20, 30];
        let mut buf = [0u8; 12];
        let n = arr.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 12); // 3 * 4 bytes, NO length prefix
        let (decoded, consumed) = <[u32; 3]>::decode_cdr2_le(&buf).unwrap();
        assert_eq!(decoded, arr);
        assert_eq!(consumed, 12);
    }

    #[test]
    fn test_array_single_element() {
        let arr: [u8; 1] = [0xFF];
        let mut buf = [0u8; 1];
        let n = arr.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 1);
        let (decoded, _) = <[u8; 1]>::decode_cdr2_le(&buf).unwrap();
        assert_eq!(decoded, [0xFF]);
    }

    // ================================================================
    // Option<T> tests (GAP-003)
    // ================================================================

    #[test]
    fn test_option_none_roundtrip() {
        let val: Option<u32> = None;
        let mut buf = [0u8; 8];
        let n = val.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 1);
        assert_eq!(buf[0], 0);
        let (decoded, consumed) = Option::<u32>::decode_cdr2_le(&buf[..n]).unwrap();
        assert_eq!(decoded, None);
        assert_eq!(consumed, 1);
    }

    #[test]
    fn test_option_some_roundtrip() {
        let val: Option<u32> = Some(42);
        let mut buf = [0u8; 8];
        let n = val.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 5); // 1 flag + 4 u32
        assert_eq!(buf[0], 1);
        let (decoded, consumed) = Option::<u32>::decode_cdr2_le(&buf[..n]).unwrap();
        assert_eq!(decoded, Some(42));
        assert_eq!(consumed, 5);
    }

    #[test]
    fn test_option_invalid_flag() {
        let buf = [2u8, 0, 0, 0, 0];
        let result = Option::<u32>::decode_cdr2_le(&buf);
        assert!(result.is_err());
    }

    // ================================================================
    // BTreeMap<K, V> tests (GAP-007)
    // ================================================================

    #[test]
    fn test_btreemap_empty_roundtrip() {
        let map: std::collections::BTreeMap<u32, u32> = std::collections::BTreeMap::new();
        let mut buf = [0u8; 64];
        let n = map.encode_cdr2_le(&mut buf).unwrap();
        assert_eq!(n, 4); // just the length prefix
        let (decoded, consumed) =
            std::collections::BTreeMap::<u32, u32>::decode_cdr2_le(&buf[..n]).unwrap();
        assert!(decoded.is_empty());
        assert_eq!(consumed, 4);
    }

    #[test]
    fn test_btreemap_populated_roundtrip() {
        let mut map = std::collections::BTreeMap::new();
        map.insert("alpha".to_string(), 1i32);
        map.insert("beta".to_string(), 2i32);
        let mut buf = [0u8; 256];
        let n = map.encode_cdr2_le(&mut buf).unwrap();
        let (decoded, consumed) =
            std::collections::BTreeMap::<String, i32>::decode_cdr2_le(&buf[..n]).unwrap();
        assert_eq!(decoded, map);
        assert_eq!(consumed, n);
    }

    #[test]
    fn test_btreemap_deterministic() {
        // BTreeMap iteration is sorted -- encoding must be deterministic
        let mut map1 = std::collections::BTreeMap::new();
        map1.insert(3u32, 30u32);
        map1.insert(1u32, 10u32);
        map1.insert(2u32, 20u32);

        let mut map2 = std::collections::BTreeMap::new();
        map2.insert(1u32, 10u32);
        map2.insert(2u32, 20u32);
        map2.insert(3u32, 30u32);

        let mut buf1 = [0u8; 64];
        let mut buf2 = [0u8; 64];
        let n1 = map1.encode_cdr2_le(&mut buf1).unwrap();
        let n2 = map2.encode_cdr2_le(&mut buf2).unwrap();
        assert_eq!(&buf1[..n1], &buf2[..n2]);
    }

    #[test]
    fn test_str_encode() {
        let original: &str = "test";
        let mut buf = vec![0u8; 256];

        let encoded_len = original
            .encode_cdr2_le(&mut buf)
            .expect("Encode should succeed");
        assert_eq!(encoded_len, 9); // 4 + 4 + 1

        // Should be decodable as String
        let (decoded, _) =
            String::decode_cdr2_le(&buf[..encoded_len]).expect("Decode should succeed");
        assert_eq!(decoded, "test");
    }
}
